<?php

namespace inventarioBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * TabInventEntradaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class TabInventEntradaRepository extends \Doctrine\ORM\EntityRepository {
}
