<?php

namespace inventarioBundle\Repository;

/**
 * TGeneraProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TGeneraProductRepository extends \Doctrine\ORM\EntityRepository
{
}
