<?php

namespace inventarioBundle\Repository;

/**
 * TGeneraAlmacenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TGeneraAlmacenRepository extends \Doctrine\ORM\EntityRepository
{
}
