<?php

namespace inventarioBundle\Repository;

/**
 * TSalidaLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TSalidaLogRepository extends \Doctrine\ORM\EntityRepository
{
}
